sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: xK3WG/1OA/VFBrzfD+VFvGpxim27ptmghR3WML53oIUSayexQGwj/x+XWEuohKMqcrf7djfo0bJUT7+sNvrBUca3fYUklrwH7jyw8zh0R9C3rNQSG1+JC2Tph8iDmkw2jhNYMqDWSrW/JmcO2qkuW7xBQA6q/OA43vEreJZQbKHoe3CZ1M80rqMTkAH2ziVokwuubZJvXrYGl6qI4mustHLNtTCCTNM0K/MAXt8qDQSld9fQrXhYZ28SFHweO4Bkt04dBgbDS6Rt9040lYimO14qX8GNh7qSrZzhm2zYuSbaiBsmW3t1OGJ2Akmn7Y1u1LnVVVTmg+XliJtTEfVcgP7d8ZXBvpLKMalJHeFAdshcVGuQU9K0V/tHC6zXbixMmaqLzKM3wGab2NNmAp07EAkHzYpWTQTiOj9X4Zy/xUCDR4IK0BCtsbGWptoy9THl8jY29RrhEE//G5oGQUB3H64rmLmPpCu3AEUUM521R2krgcrkJzAVpgAo4mlv9Kuc8/wdIKpZwzYu+6g+KDiW9vQOJJu0G+0flh0ibH2U0XmLabgIs62DXk3tWdNjbRTijNKpw6fTWNQPcMWvVTDicbPrydZcOa8MdBFoP2DF2UMiZDL6JA2wBJM7EYZWGTQBVPMIMx/4DETiVaYONNiNzDv06dFsvHaoQ/uZdZoV148=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Secret-Sharer_220
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy